baseurl: "https://mverwaerde.github.io/naissance/"
title: "Liste de naissance"
languageCode: "fr-fr"

permalinks:
  pages: /:slug

params:
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style: "green"
  
  # Contact form uses www.formspree.io
  endpoint: "xnqlwaal"

  # Personal International Bank Account Number
  identity: "M. JARDIN FLORENT MARINE"
  iban: "FR76 3007 6029 5830 9744 0030 075"

  # Nav links in the side bar
  navlinks:
  - name: "Notre démarche"
    url: "demarche/"
    
  - name: "Nous contacter"
    url: "contacter/"

  social:
    github: "https://github.com/mverwaerde/naissance/"